### ISSUE TITLE
Why i can share text and link in weChat?

### ISSUE THREAD

**Issue by kabirhossainbd** [chejdj/social_share#2]
Why i can share text and link in weChat please could you fix it or any example code to share with me?

this is my console:
sendUsingPendingIntent fail, ex = com.pplingo.connect: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MicroMsg.SDK.MMessageAct(22887): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
D/MicroMsg.SDK.MMessageAct(22887): send mm message, intent=Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXEntryActivity (has extras) }
I/ViewRootImpl@291f09[MainActivity](22887): MSG_WINDOW_FOCUS_CHANGED 0 0

**Comment by chejdj** [comment]
@kabirhossainbd Share text and link to weChat. Your app should be registered in weChat.
register address: https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Share_and_Favorites/Share_and_Favorites.html

**Comment by chejdj** [comment]
For the example project, I hide the  'key.properties' some passwords. Because some online app  use it. I can't provide

**Comment by kabirhossainbd** [comment]
> For the example project, I hide the 'key.properties' some passwords. Because some online app use it. I can't provide

But you wrote in your documentation that it will work as link text, just only images work, so if you give any solution for share link using your plugin that will be great help

**Comment by chejdj** [comment]
> > For the example project, I hide the 'key.properties' some passwords. Because some online app use it. I can't provide
> 
> But you wrote in your documentation that it will work as link text, just only images work, so if you give any solution for share link using your plugin that will be great help

You can use the system share method(share webpage to native) if you wan't register on wechat platform.
